apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  POSTGRES_DB: ecommerce_db
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  PRODUCT_DB: product_db
  ORDER_DB: order_db
  PRODUCT_SERVICE_URL: http://product-service:8081
  ORDER_SERVICE_URL: http://order-service:8082
