apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ecommerce
type: Opaque
data:
  # base64 encoded values
  # ecommerce_user -> ZWNvbW1lcmNlX3VzZXI=
  # ecommerce_pass -> ZWNvbW1lcmNlX3Bhc3M=
  POSTGRES_USER: ZWNvbW1lcmNlX3VzZXI=
  POSTGRES_PASSWORD: ZWNvbW1lcmNlX3Bhc3M=
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ecommerce
type: Opaque
data:
  # mySecretKeyForJWTTokenGenerationAndValidation2024
  JWT_SECRET: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uMjAyNA==
